Repository Capstone-OpenStep/BE-OpenStep, pull requests merged in 2025-05, with the labels that each got.

#36 Feat: 트렌딩 및 특정 레포지토리 조회 기능 구현
  docker-compose-deploy.yml
  src/main/java/com/chungang/capstone/openstep/OpenstepApplication.java
  src/main/java/com/chungang/capstone/openstep/domain/Rank/entity/Rank.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/controller/RepoController.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/converter/RepoConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/dto/GitHubGraphQLRequest.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/dto/GitHubRepoResponse.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/dto/RepoResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/dto/RespResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/entity/Repo.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/repository/RepoRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/service/GitHubGraphQLService.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/service/RepoQueryService.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/exception/handler/RepoHandler.java
  src/main/java/com/chungang/capstone/openstep/global/config/RestTemplateConfig.java
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
Labels: :sparkles: Feature

#37 Feat: Github Oauth 로그인 구현
  src/main/java/com/chungang/capstone/openstep/OpenstepApplication.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/controller/GithubOAuthController.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/converter/MemberConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/dto/GithubOAuthDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/dto/LoginResult.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/dto/MemberResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/repository/MemberRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/service/GithubOauthService.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
Labels: :sparkles: Feature

#38 Refactor: buildGradle 스프링부트 버전 수정
  build.gradle
Labels: :recycle: Refactor

#42 Feat: 트렌딩 이슈 리스트 조회 API 기능 구현
  src/main/java/com/chungang/capstone/openstep/domain/Github/dto/GitHubGraphQLRequest.java
  src/main/java/com/chungang/capstone/openstep/domain/Github/dto/GitHubIssueResponse.java
  src/main/java/com/chungang/capstone/openstep/domain/Github/dto/GitHubRepoResponse.java
  src/main/java/com/chungang/capstone/openstep/domain/Github/service/GitHubGraphQLService.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/controller/IssueController.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/converter/IssueConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/dto/IssueResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/entity/Issue.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/repository/IssueRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/service/IssueQueryService.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/repository/RepoRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/service/RepoQueryService.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/exception/handler/IssueHandler.java
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
Labels: :sparkles: Feature

#44 Feat: 트렌딩 특정 이슈 상세 조회 API 구현
  src/main/java/com/chungang/capstone/openstep/domain/Issue/controller/IssueController.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/converter/IssueConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/dto/IssueResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/service/IssueQueryService.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
Labels: :sparkles: Feature

#46 Feat: OpenAPI 연동 후 레포지토리/이슈 요약 기능 구현 및 summary 필드 저장
  build.gradle
  src/main/java/com/chungang/capstone/openstep/domain/Issue/converter/IssueConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/dto/IssueResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/entity/Issue.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/service/IssueQueryService.java
  src/main/java/com/chungang/capstone/openstep/domain/OpenAI/controller/SummaryController.java
  src/main/java/com/chungang/capstone/openstep/domain/OpenAI/service/OpenAIService.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/converter/RepoConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/dto/RepoResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/entity/Repo.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/service/RepoQueryService.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/chungang/capstone/openstep/global/config/OpenAIConfig.java
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
Labels: :sparkles: Feature

#50 Feat: 레포지토리 북마크 설정 및 조회 관련 API 구현
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/controller/BookmarkController.java
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/converter/BookmarkConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/dto/BookmarkResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/entity/Bookmark.java
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/repository/BookmarkRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/service/BookmarkCommandService.java
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/service/BookmarkQueryService.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/controller/RepoController.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
Labels: :sparkles: Feature

#51 Refactor: 북마크 관련 API 메소드 수정
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/controller/BookmarkController.java
Labels: :recycle: Refactor

#55 Refactor: CORS 코드 수정
  dump.rdb
  src/main/java/com/chungang/capstone/openstep/domain/Repo/controller/RepoController.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/converter/RepoConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/dto/RepoResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/repository/RepoRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/service/RepoQueryService.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/chungang/capstone/openstep/global/config/RedisConfig.java
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
Labels: bug

#56 Fix: CORS handling 코드 수정
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
Labels: bug

#57 Fix: GitHub OAuth 사용자 정보 요청 시 Accept 헤더 추가
  src/main/java/com/chungang/capstone/openstep/domain/Member/service/GithubOauthService.java
Labels: bug

#58 Fix: GitHub OAuth 사용자 정보 요청 시 Accept 헤더 추가
  src/main/java/com/chungang/capstone/openstep/domain/Member/service/GithubOauthService.java
Labels: bug

#59 Feat: 깃허브 로그인 url요청 API 구현
  src/main/java/com/chungang/capstone/openstep/domain/Member/controller/GithubOAuthController.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/dto/MemberResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/service/GithubOauthService.java
Labels: :sparkles: Feature

#61 Feat: 이메일 회원가입, 로그인, 로그아웃, 액세스 토큰 재할당 API 구현
  src/main/java/com/chungang/capstone/openstep/domain/Member/controller/MemberController.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/converter/MemberConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/dto/MemberRequestDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/dto/MemberResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/repository/MemberRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/service/AuthService.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/exception/handler/MemberHandler.java
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
  src/main/java/com/chungang/capstone/openstep/global/security/filter/EmailPasswordAuthenticationFilter.java
  src/main/java/com/chungang/capstone/openstep/global/security/principal/PrincipalDetails.java
  src/main/java/com/chungang/capstone/openstep/global/security/principal/PrincipalDetailsService.java
  src/main/java/com/chungang/capstone/openstep/global/security/provider/JwtTokenProvider.java
  src/main/java/com/chungang/capstone/openstep/global/security/provider/TokenInfo.java
Labels: :sparkles: Feature

#62 Refactor: 사용자 관심언어 및 관심분야 선택 로직 변경
  src/main/java/com/chungang/capstone/openstep/domain/Member/controller/MemberController.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/converter/MemberConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/dto/MemberRequestDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/dto/MemberResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/entity/Domain.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/entity/Member.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/entity/MemberDomain.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/entity/MemberLanguage.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/entity/Skill.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/repository/DomainRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/repository/MemberDomainRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/repository/MemberLanguageRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/repository/MemberSkillRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/repository/SkillRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/service/MemberCommandService.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/service/MemberQueryService.java
  src/main/java/com/chungang/capstone/openstep/domain/common/InterestDomain.java
  src/main/java/com/chungang/capstone/openstep/domain/common/InterestLanguage.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
Labels: :recycle: Refactor

#63 Refactor: 관심분야 선택 로직 수정 및 사용자의 관심언어, 분야 조회 API 수정
  src/main/java/com/chungang/capstone/openstep/domain/Member/controller/MemberController.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/service/MemberCommandService.java
  src/main/java/com/chungang/capstone/openstep/domain/common/InterestDomain.java
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
Labels: :recycle: Refactor

#64 Fix: API response 오타 수정
  src/main/java/com/chungang/capstone/openstep/domain/Member/dto/MemberResponseDTO.java
Labels: :recycle: Refactor

#67 fix: 토큰을 통해 접근할 수 없던 문제 해결
  src/main/java/com/chungang/capstone/openstep/domain/Member/controller/MemberController.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/service/GithubOauthService.java
  src/main/java/com/chungang/capstone/openstep/global/security/principal/PrincipalDetailsService.java
Labels: bug

#68 이슈 할당 로직 추가
  src/main/java/com/chungang/capstone/openstep/domain/Github/service/GithubRepoService.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/controller/IssueController.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/converter/IssueConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/dto/IssueResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/service/IssueCommandService.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/service/IssueQueryService.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/controller/GithubOAuthController.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/controller/MemberController.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/entity/Member.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/service/GithubOauthService.java
  src/main/java/com/chungang/capstone/openstep/domain/Task/entity/Task.java
  src/main/java/com/chungang/capstone/openstep/domain/Task/entity/TaskStatus.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/exception/GithubRestException.java
  src/main/java/com/chungang/capstone/openstep/global/security/principal/PrincipalDetails.java
  src/main/java/com/chungang/capstone/openstep/global/security/util/SecurityUtils.java
Labels: :sparkles: Feature

#69 Refactor: PrincipalDetailsService에서 email 또는 memberId 모두 지원하도록 수정
  src/main/java/com/chungang/capstone/openstep/global/security/principal/PrincipalDetailsService.java
Labels: :recycle: Refactor

#72 Feat: 사용자 관심언어, 분야 기준 맞춤 레포지토리 추천 API 구현
  src/main/java/com/chungang/capstone/openstep/domain/Github/service/GitHubGraphQLService.java
  src/main/java/com/chungang/capstone/openstep/domain/Github/util/GitHubQueryBuilder.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/controller/RepoController.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/entity/Repo.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/service/RepoCacheService.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/service/RepoQueryService.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/chungang/capstone/openstep/global/config/RedisConfig.java
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
Labels: :sparkles: Feature

#76 Feat: 사용자 맞춤 이슈 추천 API 구현
  docker-compose-deploy.yml
  src/main/java/com/chungang/capstone/openstep/domain/Github/dto/GitHubIssueResponse.java
  src/main/java/com/chungang/capstone/openstep/domain/Github/dto/GitHubRepoResponse.java
  src/main/java/com/chungang/capstone/openstep/domain/Github/service/GitHubGraphQLService.java
  src/main/java/com/chungang/capstone/openstep/domain/Github/util/GitHubQueryBuilder.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/controller/IssueController.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/converter/IssueConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/dto/IssueResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/entity/Issue.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/repository/IssueRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/service/IssueCacheService.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/service/IssueQueryService.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/converter/RepoConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/dto/RepoResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/entity/Repo.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/repository/RepoRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/service/RepoCacheService.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/service/RepoQueryService.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
Labels: :sparkles: Feature

#78 Feat: 키워드로 트렌딩 또는 추천된 이슈 검색하기
  src/main/java/com/chungang/capstone/openstep/domain/Issue/controller/IssueController.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/repository/IssueRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/service/IssueQueryService.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
Labels: :sparkles: Feature

#79 Refactor: 트렌딩 레포 및 이슈 조회 로직 수정
  src/main/java/com/chungang/capstone/openstep/domain/Github/dto/GitHubRepoResponse.java
  src/main/java/com/chungang/capstone/openstep/domain/Github/service/GitHubGraphQLService.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/service/IssueQueryService.java
Labels: :recycle: Refactor

#91 Refactor: 레포지토리 소유자, 이슈, 깃허브 사용자 아바타 url 반환 추가
  src/main/java/com/chungang/capstone/openstep/domain/Github/dto/GitHubIssueResponse.java
  src/main/java/com/chungang/capstone/openstep/domain/Github/dto/GitHubRepoResponse.java
  src/main/java/com/chungang/capstone/openstep/domain/Github/dto/PullRequestResponse.java
  src/main/java/com/chungang/capstone/openstep/domain/Github/service/GitHubGraphQLService.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/converter/IssueConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/dto/IssueResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/entity/Issue.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/service/IssueQueryService.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/dto/GithubOAuthDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/entity/Member.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/service/GithubOauthService.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/converter/RepoConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/dto/RepoResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/entity/Repo.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/service/RepoQueryService.java
Labels: :recycle: Refactor

#92 Refactor: 북마크 설정, 삭제, 조회 API의 대상을 레포지토리에서 이슈로 변경
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/controller/BookmarkController.java
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/converter/BookmarkConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/dto/BookmarkResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/entity/Bookmark.java
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/repository/BookmarkRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/service/BookmarkCommandService.java
  src/main/java/com/chungang/capstone/openstep/domain/Bookmark/service/BookmarkQueryService.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/entity/Issue.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
Labels: :recycle: Refactor

#93 Refactor: 관심분야, 관심언어 설정 관련 API 엔드포인트 수정
  src/main/java/com/chungang/capstone/openstep/domain/Member/controller/MemberController.java
  src/main/java/com/chungang/capstone/openstep/global/config/SecurityConfig.java
Labels: :recycle: Refactor

#99 Refactor: 사용자 맞춤 이슈 추천 조건 완화 및 로그 개선
  src/main/java/com/chungang/capstone/openstep/domain/Issue/service/IssueQueryService.java
  src/main/java/com/chungang/capstone/openstep/domain/Repo/service/RepoQueryService.java
Labels: :recycle: Refactor
