Repository Capstone-OpenStep/BE-OpenStep, pull requests merged in 2025-06, with the labels that each got.

#104 Refactor: 키워드, 언어, 업데이트 기간 필터로 이슈 검색하도록 기능 수정
  src/main/java/com/chungang/capstone/openstep/domain/Github/dto/GitHubIssueResponse.java
  src/main/java/com/chungang/capstone/openstep/domain/Github/service/GitHubGraphQLService.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/controller/IssueController.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/converter/IssueConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/dto/IssueResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/service/IssueQueryService.java
  src/main/java/com/chungang/capstone/openstep/domain/Rank/entity/BadgeType.java
  src/main/java/com/chungang/capstone/openstep/domain/common/UpdatePeriod.java
Labels: :recycle: Refactor

#107 Refactor: 트렌딩 이슈, 사용자 맞춤 이슈, 키워드 검색 이슈 조회시 페이징으로 변횐
  src/main/java/com/chungang/capstone/openstep/domain/Issue/controller/IssueController.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/service/IssueCacheService.java
  src/main/java/com/chungang/capstone/openstep/domain/Issue/service/IssueQueryService.java
Labels: :recycle: Refactor

#113 Refactor: 이슈 검색 기능 비로그인 사용자도 접근 가능하도록 수정
  src/main/java/com/chungang/capstone/openstep/domain/Issue/controller/IssueController.java
Labels: :recycle: Refactor

#118 Feat: 로그인한 사용자의 프로필 조회 API 구현
  src/main/java/com/chungang/capstone/openstep/domain/Github/dto/GitHubUserProfile.java
  src/main/java/com/chungang/capstone/openstep/domain/Github/dto/GitHubUserProfileResponse.java
  src/main/java/com/chungang/capstone/openstep/domain/Github/service/GitHubGraphQLService.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/controller/MemberController.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/converter/MemberConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/dto/MemberResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/entity/Member.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/service/MemberQueryService.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
Labels: :sparkles: Feature

#119 Refactor: Task status 조회시 MERGED 상태 조회 오류 수정
  src/main/java/com/chungang/capstone/openstep/domain/Github/service/GitHubStatusResolverServiceImpl.java
Labels: :recycle: Refactor

#122 FEAT: 업적 반환 로직 추가 및 PR 인코딩 방식 변경
  src/main/java/com/chungang/capstone/openstep/domain/Github/service/GithubRestServiceImpl.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/controller/MemberController.java
  src/main/java/com/chungang/capstone/openstep/domain/Member/entity/Member.java
  src/main/java/com/chungang/capstone/openstep/domain/Task/converter/TaskConverter.java
  src/main/java/com/chungang/capstone/openstep/domain/Task/dto/TaskResponseDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/Task/service/TaskQueryService.java
  src/main/java/com/chungang/capstone/openstep/domain/achievement/dto/AchievementDTO.java
  src/main/java/com/chungang/capstone/openstep/domain/achievement/entity/MemberAchievement.java
  src/main/java/com/chungang/capstone/openstep/domain/achievement/listener/AchievementEventListener.java
  src/main/java/com/chungang/capstone/openstep/domain/achievement/repository/MemberAchievementRepository.java
  src/main/java/com/chungang/capstone/openstep/domain/achievement/service/AchievementService.java
  src/main/java/com/chungang/capstone/openstep/domain/achievement/service/AchievementServiceImpl.java
  src/main/java/com/chungang/capstone/openstep/global/apiPayload/code/status/SuccessStatus.java
Labels: bug, :sparkles: Feature, :gear: Chore
